test:
	./compiler test.lang out
	./out

threading:
	./compiler threading.lang out
	./out

persondb:
	./compiler persondb.lang out
	./out

webserver:
	./compiler webserver.lang out
	./out

socket_tcp:
	./compiler socket_tcp.lang out
	./out

floats:
	./compiler floatsExample.lang out
	./out

features:
	./compiler features.lang out
	./out

tictactoe:
	./compiler tictactoe.lang out
	./out

file_nav:
	./compiler file_nav.lang out
	./out

tcp_conv_server:
	./compiler tcpConv/tcpConvServer.lang out
	./out

tcp_conv_client:
	./compiler tcpConv/tcpConvClient.lang out
	./out

clean:
	rm -f out