test:
	./compiler test.lang out
	./out

threading:
	./compiler threading.lang out
	./out

persondb:
	./compiler persondb.lang out
	./out

webserver:
	./compiler webserver.lang out
	./out

socket_tcp:
	./compiler socket_tcp.lang out
	./out

floats:
	./compiler floatsExample.lang out
	./out

features:
	./compiler features.lang out
	./out


clean:
	rm -f out